finished creating user and statig find suer

diff --git a/toolz b/toolz
--- a/toolz
+++ b/toolz
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 GREEN="\033[32m"
-YELLOW="\033[33m"
 RESET="\033[0m"
 
 #Main toolz program
@@ -256,26 +255,40 @@ function userManage() {
 		case "$userManagementOpt" in
 			-c)
 			read -p "Username: " newUsername
-			# Check if passowrd contains at least 2 letters and numbers
+			sudo useradd -m ${newUsername}
+			# Check if passowrd length is at leat 8 and contains at least 2 letters and numbers
+		if [[ $? == 0 ]]; then
 			while true; do	
 			read -s -p "Password: " newUserPassword	
+
 			if [[ "${#newUserPassword}" -gt 7 ]] && [[ ${newUserPassword} =~ ([a-zA-Z].*){2,} ]] && [[ ${newUserPassword} =~ ([0-9].*){2,} ]]; then
-				sudo useradd -m ${newUsername}
-				sudo passwd ${newUserPassword}
-				printf "%b\n" "${newUsername} was ${GREEN}successfully${RESET} created" 
-				break;
+				echo "$newUsername:$newUserPassword" |sudo chpasswd
+				if [[ $? == 0 ]]; then	
+					printf "%b\n" "${newUsername} was ${GREEN}successfully${RESET} created" 
+					break;
+				else
+					echo "Something went wrong"
+					break;
+				fi
 			else
-				printf "Password must be at least 8 characters long and include at least 2 letters
+				printf "\nPassword must be at least 8 characters long and include at least 2 letters
 and 2 numbers\n"
 
 
 			fi
-				
-
-
 
 			done
+		fi
 			;;
+			-f)
+			read -p "Username: " findUser
+
+			if [[ -z $finduser ]]; then
+				echo "Invalid option.. Exiting"
+				exit 1
+			fi
+			;;		
+				
 			*)
 			echo "Invalid option.. Exiting" ;;
 
